comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%

    patch:
      default:
        # I'm just using the patch coverage as information; no requirements
        # necessary.
        target: 0%
